libris/xl_auth

Jenkinsfile
README.rst
xl_auth/commands.py

This pull request adds CI for xl_auth (resolves #7).
1. Read version, branch name and stuff (to determine what kind of build it is, develop/release-candidate/release)
2. Create py27 and py35 virtualenvs using SCL (necessary Python dependencies documented in this mblomdahl/jenkins-up#26 pull request earlier today)
3. Runs ESLint and pytest using Python 2.7 and 3.5
4. If previous steps succeeds— and branch type is `release` or `master` —a Docker image is built, otherwise build stage is skipped
I've yet to be introduced to adding dependencies on jenkins.kb.se, so for the moment it's running on my personal Jenkins server (no login needed). See last build from this branch here:
- http://jenkins.smithmicro.io:8080/blue/organizations/jenkins/xl_auth-multibranch/detail/feature%2Fjenkinsfile/5/pipe …

Feature/Jenkinsfile (Fixes #7)

---

migrations/env.py
migrations/versions/bbfcebd395a0_replace_first_name_last_name_with_full_.py
tests/end2end/test_logging_in.py
tests/end2end/test_registering.py
tests/factories.py
tests/forms/test_login.py
tests/forms/test_register.py
tests/models/test_user.py
xl_auth/public/forms.py
xl_auth/public/views.py
xl_auth/templates/footer.html
xl_auth/templates/nav.html
xl_auth/templates/public/register.html
xl_auth/templates/users/members.html
xl_auth/user/forms.py
xl_auth/user/models.py

This pull request resolves #9, applying the following changes:
1. `username` column removed with `email` repurposed in its place
2. replaced `first_name`/`last_name` with `full_name`
3. set size of text columns to 255
How to verify it works (assuming you already followed setup steps in #4):
1. switch branch to this one and pull latest changes
2. make sure the app is stopped
3. export envvars (if not already in place)
3. run Alembic db ~~migration~~ **upgrade**
4. start the app
```bash
export FLASK_APP=autoapp.py
export FLASK_DEBUG=1
flask db upgrade
flask run
```
Then you should see a modified register screen on http://localhost:5000/register/, like so:

Feature/Replace `username` with `email`

---

tests/conftest.py
tests/forms/test_permission.py
tests/models/test_permission.py
xl_auth/permission/forms.py
xl_auth/permission/models.py

This pull request adds form validation for adding and modifying permissions.

Feature/Permission Forms

---

messages.pot
migrations/versions/564f2b578774_add_cataloguing_admin_to_permissions_.py
migrations/versions/c336664ee988_rename_catalogue_admin_column_to_.py
migrations/versions/cb414ea80248_make_permissions_column_naming_.py
tests/end2end/test_registering_permission.py
tests/forms/test_permission.py
tests/models/test_permission.py
xl_auth/permission/forms.py
xl_auth/permission/models.py
xl_auth/permission/views.py
xl_auth/templates/permissions/edit.html
xl_auth/templates/permissions/home.html
xl_auth/templates/permissions/register.html
xl_auth/translations/sv/LC_MESSAGES/messages.po

Add Cataloguing Administrator permission

---

README.rst
tests/conftest.py
tests/end2end/test_registering_user.py
tests/factories.py
tests/forms/test_user.py
xl_auth/app.py
xl_auth/commands.py
xl_auth/public/views.py
xl_auth/templates/401.html
xl_auth/templates/nav.html
xl_auth/templates/users/home.html
xl_auth/templates/users/register.html
xl_auth/user/forms.py
xl_auth/user/views.py

In preparation of #48, the following has been done:
* Remove public account registration
* Move registration to User model
* Update tests to use super user
* Add command to create user

Fix user permissions baseline

---

assets/css/style.less
package-lock.json
package.json
webpack.config.js
xl_auth/templates/nav.html
xl_auth/templates/public/home.html

* Add kungbib-styles package on top of bootstrap.
* Add navbar logotype
* Change app main style file to .less format

Add kungbib-styles package

---

assets/css/style.less
messages.pot
tests/end2end/test_deleting_permission.py
tests/end2end/test_editing_collection.py
tests/end2end/test_editing_permission.py
tests/end2end/test_registering_collection.py
tests/end2end/test_registering_permission.py
xl_auth/templates/layout.html
xl_auth/templates/nav.html
xl_auth/templates/public/home.html
xl_auth/translations/sv/LC_MESSAGES/messages.po

* Hide navbar when logged out
* Move login into body-content
* Add some helpful links
* Add translation for service name
#6 #22

Update layout of login and home page

---

assets/css/style.less
messages.pot
tests/end2end/test_editing_user.py
xl_auth/templates/permissions/home.html
xl_auth/templates/users/home.html
xl_auth/translations/sv/LC_MESSAGES/messages.po

* Show Yes/No instead of True/False
* Color styling (red/green)
*"Active" flag not included*

Styled Yes/No on bool values in tables

---

assets/css/style.less
messages.pot
tests/end2end/test_editing_collection.py
tests/end2end/test_registering_collection.py
xl_auth/collection/views.py
xl_auth/templates/collections/home.html
xl_auth/translations/sv/LC_MESSAGES/messages.po

* Split existing and inactive in two tables
* Remove edit on inactive items
* Switch edit button to icon
* Add vertical navigation anchors
* Truncate long names
* Add links to replaced_by cells

Update collections layout

---

xl_auth/templates/public/home.html
xl_auth/translations/sv/LC_MESSAGES/messages.po

* Remove template text
* Remove customer service box
* Update welcome message

Update home page layout

---

ansible/Vagrantfile
ansible/roles/xl_auth/defaults/main.yml
ansible/roles/xl_auth/tasks/main.yml
messages.pot
tests/end2end/test_editing_collection.py
xl_auth/templates/public/home.html
xl_auth/templates/users/profile.html
xl_auth/translations/sv/LC_MESSAGES/messages.po

#39 Use full Docker image name, use new `--admin-email` option for data import

Fixing deployment steps

---

assets/css/style.less
messages.pot
tests/end2end/test_editing_user.py
xl_auth/templates/collections/home.html
xl_auth/templates/footer.html
xl_auth/templates/permissions/home.html
xl_auth/templates/public/about.html
xl_auth/templates/public/home.html
xl_auth/templates/users/home.html
xl_auth/translations/sv/LC_MESSAGES/messages.po
xl_auth/user/views.py

* Fix login and home page text
* Fix contact email
* Add cell breaking
* Split user list in two (active/inactive)
* Removed customer service link
#61

Layout fixes and user list split

---

xl_auth/permission/forms.py

Courtesy of @kaipoykio. Thanks! 😸

Logic error, fixes #76

---

README.rst
messages.pot
migrations/versions/f3e929832ba3_add_modified_at_and_last_login_at_fields.py
package-lock.json
package.json
tests/end2end/test_logging_in.py
tests/models/test_client.py
tests/models/test_collection.py
tests/models/test_permission.py
tests/models/test_user.py
xl_auth/client/models.py
xl_auth/collection/models.py
xl_auth/permission/models.py
xl_auth/public/views.py
xl_auth/templates/users/home.html
xl_auth/translations/sv/LC_MESSAGES/messages.po
xl_auth/user/models.py

Adds `modified_at` + `last_login_at` from #78. The `created_at` might be rather convoluted, the way we initially envisioned it... Let's defer that until we've done some thinking. :)

Feature/Last Login

---

messages.pot
migrations/versions/e18d13a9f276_add_oauth2_tokens.py
tests/conftest.py
tests/end2end/test_listing_grant.py
tests/end2end/test_listing_token.py
tests/factories.py
tests/models/test_grant.py
tests/models/test_token.py
xl_auth/app.py
xl_auth/database.py
xl_auth/grant/__init__.py
xl_auth/grant/models.py
xl_auth/grant/views.py
xl_auth/templates/grants/home.html
xl_auth/templates/tokens/home.html
xl_auth/token/__init__.py
xl_auth/token/models.py
xl_auth/token/views.py
xl_auth/translations/sv/LC_MESSAGES/messages.po

Add OAuth2 Grant and Token models

---

README.rst

Corrected description + up-to-date database diagram

---

tests/end2end/test_oauth_client_flow.py
xl_auth/oauth/views.py
xl_auth/translations/sv/LC_MESSAGES/messages.po

Bugfix/Oauth Verify Permissions Response

---

README.rst
messages.pot
migrations/versions/7f3f1a931278_add_tos_approved_at_to_user.py
tests/end2end/test_public_logging_in.py
tests/factories.py
tests/forms/test_user_approve_tos.py
tests/forms/test_user_register.py
tests/models/test_user.py
xl_auth/commands.py
xl_auth/public/views.py
xl_auth/templates/users/approve_tos.html
xl_auth/translations/sv/LC_MESSAGES/messages.po
xl_auth/user/forms.py
xl_auth/user/models.py
xl_auth/user/views.py

Translations on the way!
Resolves #112 .

Feature/Approve ToS

---

messages.pot
tests/end2end/test_user_view.py
tests/models/test_user.py
xl_auth/templates/users/inspect.html
xl_auth/templates/users/simple_view.html
xl_auth/templates/users/view.html
xl_auth/translations/sv/LC_MESSAGES/messages.po
xl_auth/user/forms.py
xl_auth/user/models.py
xl_auth/user/views.py

Feature/#109 Code review fixes iteration 1

---

README.rst
xl_auth/commands.py

#113 Exception for SEK while loading Voyager permission model

---

messages.pot
tests/end2end/test_public_reset_password.py
tests/forms/test_public_forgot_password.py
xl_auth/public/forms.py
xl_auth/settings.py
xl_auth/translations/sv/LC_MESSAGES/messages.po
xl_auth/user/models.py

Add limit for active password resets

---

README.rst

Update quickstart readme

---

messages.pot
xl_auth/templates/nav.html
xl_auth/translations/sv/LC_MESSAGES/messages.po

Add text to logout button, hide icons when collapsed menu

---

Jenkinsfile
tests/end2end/test_public_logging_in.py
tests/forms/test_user_administer.py
xl_auth/public/views.py

Feature/429 with X-Username

---

tests/models/test_user.py

(Also test very long password.)

Add test for passwords containing UTF-8 chars

---

Dockerfile
ansible/roles/xl_auth/tasks/main.yml
gunicorn_conf.py
requirements/prod.txt
xl_auth/commands.py

This resolves some stuff in #180, related to #179 and #175

Feature/Prod Run Cmd 2

---

Procfile
assets/css/style.less
xl_auth/templates/nav.html
xl_auth/templates/public/home.html

Fix WCAG 2.0 issues, as reported by Chrome aXe extension, excluding those inherent to `kungbib-styles-1.2.4`.
@oBlissing @bjarman Please put up a pull request updating the xl_auth KB style dependency when colors have been properly adjusted.

Fix WCAG 2.0 issues

---

messages.pot
xl_auth/templates/collections/home.html
xl_auth/templates/public/home.html
xl_auth/translations/sv/LC_MESSAGES/messages.po

This pull request resolves UX issues #176 and #173.

Feature/Copy Updates

---

tests/models/test_grant.py
tests/models/test_permission.py
tests/models/test_token.py
tests/models/test_user.py
xl_auth/app.py
xl_auth/collection/models.py
xl_auth/commands.py
xl_auth/database.py
xl_auth/oauth/grant/models.py
xl_auth/oauth/token/models.py
xl_auth/permission/models.py
xl_auth/user/models.py

Add CLI tool for purging all user info from system

---

Dockerfile
README.rst
ansible/roles/xl_auth/tasks/main.yml
ansible/roles/xl_auth/tasks/xl_auth_install.yml
ansible/roles/xl_auth/templates/xl_auth.service.j2
requirements/dev.txt
requirements/prod.txt

Click 7.0 replaces underscores with dashes in flask command names.
Update scripts and instructions.
Specify exact version in `click` dependency to avoid future surprises.

Click 7.0 replaces underscores with dashes in flask command names.
